data:
    index: 0
    root: /Users/rvh/Documents/WCM/data/ISLES2024
model:
    alpha: 0.5
    criterion_img: MultiscaleNormalizedCrossCorrelation2d
    criterion_img_kwargs:
        patch_sizes: [null, 13]
        patch_weights: [0.5, 0.5]
    criterion_msk: GeneralizedDiceLoss
    detector_dist: 400
    detector_size: [256, 256]
    detector_spacing: [1.2, 1.2]
    lambda_so3: 0
    multiplier: 1000
    num_iter: 400
    optimizer: Adam
    optimizer_kwargs:
        lr: 1e-4
    scheduler: OneCycleLR
    scheduler_kwargs:
        max_lr: 1e-2
        total_steps: 400
    sigmas: [25, 11, 25]
    timestamp: pre
