data:
    index: 0.5
    root: /ministorage/roel/nnUNet_raw/Dataset004_ISLES2024
model:
    alpha: 0.5
    criterion_img: MultiscaleNormalizedCrossCorrelation2d
    criterion_img_kwargs:
        patch_sizes: [null, 13]
        patch_weights: [0.5, 0.5]
    criterion_msk: GeneralizedDiceLoss
    detector_dist: 400
    detector_size: [256, 256]
    detector_spacing: [1.2, 1.2]
    lambda_so3: 0
    multiplier: 1000
    num_iter: 500
    optimizer: Adam
    optimizer_kwargs:
        lr: 7.5e-3
    scheduler: StepLR
    scheduler_kwargs:
        step_size: 25
        gamma: 0.9
    sigmas: [1.0, 11.0, 11.0, 11.0]
    timestamp: pre
